version: "3"
networks:
  ipfs:
    name: private-ipfs

services:
  bootstrap_node:
    #image: ipfs/go-ipfs:latest
    hostname: bootstrap_node
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - bootstrap_node:/data/ipfs
      - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-network/init.sh:/usr/local/bin/start_ipfs
    ports:
      - "4002:4001"
      - "8083:8080"
      - "5001:5001"
    expose:
      - 5001
    networks:
      - ipfs

  ipfs_node:
    hostname: ipfs_node
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - ipfs_node:/data/ipfs
      - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-network/init.sh:/usr/local/bin/start_ipfs
    networks:
      - ipfs

volumes:
  bootstrap_node:
  ipfs_node:
