version: "3"
networks:
  ipfs-network:
    name: ipfs-network
services:
  bootstrap_node:
    hostname: bootstrap_node
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - bootstrap_node:/data/ipfs
      - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-network/init.sh:/usr/local/bin/start_ipfs
    ports:
      - "4002:4001"
      - "8081:8080"
      - "5002:5001"
    networks:
      - ipfs-network

  ipfs_node:
    hostname: ipfs_node
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - ipfs_node:/data/ipfs
      - ./private-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-network/init.sh:/usr/local/bin/start_ipfs
    networks:
      - ipfs-network

volumes:
  bootstrap_node:
  ipfs_node:
